development:
  adapter: postgresql
  database: boogie_development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: boogie_test
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: boogie_production
  pool: 5
  timeout: 5000